plugins {
    id 'com.android.application'
}

android {
    namespace 'com.rivto.videoultra'
    compileSdk 36

    defaultConfig {
        applicationId 'com.rivto.videoultra'
        minSdk 29
        targetSdk 35
        versionCode 12
        versionName '1.2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.media3:media3-common:1.11.0'
    implementation 'androidx.media3:media3-exoplayer:1.11.0'
    implementation 'androidx.media3:media3-ui:1.11.0'
    implementation 'androidx.media3:media3-effect:1.11.0'
    implementation 'androidx.media3:media3-transformer:1.11.0'
}
